import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/topBar/topBar.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My-Dev-Portfolio",
  keywords: "nextjs, portfolio, developer, web development, technology, computer science",
  authors: [{ name: "Richard Carvalho"}],
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <html lang="pt-br" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}> 
        <TopBar />
        {children}
      </body>
    </html>
  
}
